rtd-service:
  build: .
  container_name: 'rtd-999-99-service'
  restart: 'always'
  command: 'uwsgi'
  environment:
      UWSGI_SOCKET: '0.0.0.0:8000'
      UWSGI_MODULE: 'readthedocs.wsgi'
      UWSGI_ENV: 'DJANGO_SETTINGS_MODULE=readthedocs.settings.sqlite'
nginx-proxy:
  image: 'library/nginx:1.9.0'
  container_name: 'nginx-999-99-proxy'
  restart: 'always'
  volumes:
    - './files/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
  links:
    - 'rtd-service:rtd'
  ports:
    - '80:80'
